inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'spec/**/*'

# Don't care about frozen strings
Style/FrozenStringLiteralComment:
  Enabled: false

# Don't care about code comments (yet)
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Style/AlignHash:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: key

