inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'spec/**/*'

# Don't care about frozen strings
Style/FrozenStringLiteralComment:
  Enabled: false

# Don't care about code comments (yet)
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Style/AlignHash:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: key

Style/AlignParameters:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

# Only exclude the CLI app since we cannot split this up in the current form
Metrics/ClassLength:
  Exclude:
    - 'lib/vaulty/cli_app.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'
