dist: trusty
sudo: false
language: ruby
cache: bundler

before_install:
  - curl -sLo vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - unzip vault.zip
  - mkdir -p ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - bundle install --retry=3

env:
  - VAULT_VERSION=1.0.2
  - VAULT_VERSION=0.11.6

rvm:
  - 2.6.5
  - 2.7.0

jobs:
  allow_failures:
    - rvm: 2.7.0

script:
  - 'bundle exec rake spec'
  - 'bundle exec rubocop'

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
